./src/Algorithms/multiDetectCenter/multiDetectCenter_UnitTest_D
./src/Algorithms/faceGluon/faceGluon_UnitTest_D
./src/Algorithms/personFeat/personFeat_UnitTest_D
./src/Algorithms/faceDetectTiny/faceDetectTiny_UnitTest_D
./src/Algorithms/facialLandmark/facialLandmark_UnitTest_D
./src/Algorithms/faceMask/faceMask_UnitTest_D
./src/Algorithms/faceQuality/faceQuality_UnitTest_D
./src/Algorithms/facePose/facePose_UnitTest_D
./src/Algorithms/faceType/faceType_UnitTest_D
./src/Algorithms/faceSmoke/faceSmoke_UnitTest_D
./src/Algorithms/faceIdentify/faceIdentify_UnitTest_D
./src/Algorithms/facePhone/facePhone_UnitTest_D
./src/Algorithms/faceBasicMultiAttr/faceBasicMultiAttr_UnitTest_D
./src/Algorithms/personAttr/personAttr_UnitTest_D
./src/Algorithms/personCompleteness/personCompleteness_UnitTest_D
./src/Algorithms/personQuality/personQuality_UnitTest_D
./src/Algorithms/personScarf/personScarf_Example_D
./src/Algorithms/personUmbrella/personUmbrella_Example_D
./src/Algorithms/personHeadwear/personHeadwear_UnitTest_D
./src/Algorithms/personBag/personBag_UnitTest_D
./src/Algorithms/licenseRecog/licenseRecog_UnitTest_D
./src/Algorithms/vehicleAttr/vehicleAttr_UnitTest_D
./src/Algorithms/vehicleCycleAttr/vehicleCycleAttr_UnitTest_D
./src/Algorithms/vehicleCycleFeat/vehicleCycleFeat_UnitTest_D
./src/Algorithms/vehicleFeat/vehicleFeat_UnitTest_D
