if (ATLAS_ALLOWED) 
   add_definitions(-DATLAS_ALLOWED)
   add_subdirectory(src/Algorithms/memoryDB)
   add_subdirectory(src/Algorithms/faceMask)
   add_subdirectory(src/Algorithms/faceDetectTiny)
   add_subdirectory(src/Algorithms/faceGluon)
   add_subdirectory(src/Algorithms/facePose)
   add_subdirectory(src/Algorithms/faceQuality)
   add_subdirectory(src/Algorithms/loessDetectTiny)
   add_subdirectory(src/Algorithms/rubbishDetectTiny)
   add_subdirectory(src/Algorithms/roadWater)
   add_subdirectory(src/Algorithms/roadDamage)
   add_subdirectory(src/Algorithms/fireDet)
   add_subdirectory(src/Algorithms/objectDet)
   add_subdirectory(src/Algorithms/bannerDet)
   add_subdirectory(src/Algorithms/manHoleCoverDet)
   add_subdirectory(src/Algorithms/riverFloat)
   add_subdirectory(src/Algorithms/garbageOverflow)
   add_subdirectory(src/Algorithms/illegalAccumulation)
   add_subdirectory(src/Algorithms/messyMaterials)
   add_subdirectory(src/Algorithms/advertisementDet)
   add_subdirectory(src/Algorithms/hangStreetDet)
 #  add_subdirectory(src/Algorithms/faceIdentify)
   add_subdirectory(src/Algorithms/faceType)
   add_subdirectory(src/Algorithms/facePhone)
   add_subdirectory(src/Algorithms/faceGlass)
   add_subdirectory(src/Algorithms/faceHat)
   add_subdirectory(src/Algorithms/faceSmoke)
   add_subdirectory(src/Algorithms/ageGender)
   add_subdirectory(src/Algorithms/faceBasicMultiAttr)
   add_subdirectory(src/Algorithms/facialLandmark)
   add_subdirectory(src/Algorithms/multiDetectCenter)
   add_subdirectory(src/Algorithms/personFeat)
   add_subdirectory(src/Algorithms/personAttr)
   add_subdirectory(src/Algorithms/personCompleteness)
   add_subdirectory(src/Algorithms/personHeadwear)
   add_subdirectory(src/Algorithms/vehicleFeat)
   add_subdirectory(src/Algorithms/vehicleCycleFeat)
   add_subdirectory(src/Algorithms/vehicleAttr)
   add_subdirectory(src/Algorithms/vehicleCycleAttr)
   add_subdirectory(src/Algorithms/licenseRecog)
   add_subdirectory(src/Algorithms/doubleHelmet)
   add_subdirectory(src/Algorithms/personUmbrella)
   add_subdirectory(src/Algorithms/preventionAttr)
endif (ATLAS_ALLOWED)


